test_37:
  image: python:3.7
  script: sh gitlab-ci-test.sh

test_36:
  image: python:3.6
  script: sh gitlab-ci-test.sh

test_35:
  image: python:3.5
  script: sh gitlab-ci-test.sh

test_27:
  image: python:2.7
  script: sh gitlab-ci-test.sh

test_miniconda3:
  image: continuumio/miniconda3
  script:
    - conda install conda-build conda-verify
    - conda config --add channels obob
    - conda config --add channels conda-forge
    - conda build .

test_miniconda2:
  image: continuumio/miniconda
  script:
    - conda install conda-build conda-verify
    - conda config --add channels obob
    - conda config --add channels conda-forge
    - conda build .

test_flake:
  image: python:3
  script:
    - pip install -U -r requirements.txt
    - make flake

sast:
  image: docker:stable
  variables:
    DOCKER_DRIVER: overlay2
  allow_failure: true
  services:
  - docker:stable-dind
  script:
  - export SP_VERSION=$(echo "$CI_SERVER_VERSION" | sed 's/^\([0-9]*\)\.\([0-9]*\).*/\1-\2-stable/')
  - docker run
      --env SAST_CONFIDENCE_LEVEL="${SAST_CONFIDENCE_LEVEL:-3}"
      --volume "$PWD:/code"
      --volume /var/run/docker.sock:/var/run/docker.sock
      "registry.gitlab.com/gitlab-org/security-products/sast:$SP_VERSION" /app/bin/run /code
  artifacts:
    paths: [gl-sast-report.json]
  before_script:
  - echo Hello