test_37:
  image: python:3.7
  script: sh gitlab-ci-test.sh

test_36:
  image: python:3.6
  script: sh gitlab-ci-test.sh

test_35:
  image: python:3.5
  script: sh gitlab-ci-test.sh

test_27:
  image: python:2.7
  script: sh gitlab-ci-test.sh

test_miniconda3:
  image: continuumio/miniconda3
  script:
    - conda install conda-build conda-verify
    - conda config --add channels obob
    - conda config --add channels conda-forge
    - conda build .

test_miniconda2:
  image: continuumio/miniconda
  script:
    - conda install conda-build conda-verify
    - conda config --add channels obob
    - conda config --add channels conda-forge
    - conda build .