test_37:
  image: python:3.7
  script: sh gitlab-ci-test.sh

test_36:
  image: python:3.6
  script: sh gitlab-ci-test.sh

test_35:
  image: python:3.5
  script: sh gitlab-ci-test.sh

test_27:
  image: python:2.7
  script: sh gitlab-ci-test.sh