{% set data = load_setup_py_data() %}

{% set name = 'pymatreader' %}
{% set version = data.version %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  path: .

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt
  include_recipe: False
  noarch: python

requirements:
  run:
    - python
    - h5py
    - scipy
    - numpy
    - xmltodict
    - future
  build:
    - python

test:
  imports:
    - {{ name }}
  source_files:
    - tests
  requires:
    - nose
  commands:
    - nosetests tests

about:
  home: {{ data.url }}
  license: {{ data.license }}
  license_family: BSD
  license_file: ''
  summary: {{ data.description }}
  description: '{{ data.long_description }}'
  doc_url: ''
  dev_url: ''

extra:
  recipe-maintainers: ''
